import { defineConfig } from 'tinacms';

// TinaCMS schema for the landing page. Content lives in
// content/pages/home.json and is edited visually at /admin.
//
// Local/git workflow (free, no Tina Cloud): `npm run dev` starts the editor;
// your edits are written to the JSON files, then commit & push to publish.
// To later enable editing on the *deployed* site, set TINA_CLIENT_ID +
// TINA_TOKEN (Tina Cloud free tier) or wire a self-hosted backend.
const branch =
  process.env.TINA_BRANCH ||
  process.env.GITHUB_BRANCH ||
  process.env.HEAD ||
  'master';

export default defineConfig({
  branch,
  clientId: process.env.TINA_CLIENT_ID || null,
  token: process.env.TINA_TOKEN || null,

  build: {
    outputFolder: 'admin',
    publicFolder: 'public',
  },
  media: {
    tina: {
      mediaRoot: 'assets',
      publicFolder: 'public',
    },
  },

  schema: {
    collections: [
      {
        name: 'page',
        label: 'Landing page',
        path: 'content/pages',
        format: 'json',
        // Single landing page, don't let editors add/delete page docs.
        ui: {
          allowedActions: { create: false, delete: false },
        },
        fields: [
          {
            type: 'object',
            name: 'hero',
            label: 'Hero',
            fields: [
              { type: 'string', name: 'eyebrow', label: 'Eyebrow (small label)' },
              { type: 'string', name: 'titleLine1', label: 'Title line 1' },
              { type: 'string', name: 'titleLine2', label: 'Title line 2' },
              { type: 'string', name: 'titleAccent', label: 'Title line 3 (accent colour)' },
              { type: 'string', name: 'lede', label: 'Lede paragraph', ui: { component: 'textarea' } },
              { type: 'string', name: 'disclaimer', label: 'Fork disclaimer', ui: { component: 'textarea' } },
              { type: 'image', name: 'image', label: 'Hero image' },
            ],
          },
          {
            type: 'object',
            name: 'featuresSection',
            label: 'Features heading',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'features',
            label: 'Feature rows',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.title }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Icon (emoji)' },
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
              { type: 'image', name: 'image', label: 'Screenshot' },
            ],
          },
          {
            type: 'object',
            name: 'benchmarks',
            label: 'Benchmarks',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'rows',
                label: 'Devices (table rows)',
                list: true,
                ui: { itemProps: (i) => ({ label: `${i?.device ?? ''}: ${i?.score ?? ''}` }) },
                fields: [
                  { type: 'string', name: 'device', label: 'Device' },
                  { type: 'string', name: 'url', label: 'Product page URL (optional)' },
                  { type: 'string', name: 'cores', label: 'Cores / threads' },
                  { type: 'string', name: 'score', label: 'Polaris score' },
                  { type: 'string', name: 'stacking', label: 'Stacking (Mpx/s)' },
                  { type: 'string', name: 'capture', label: 'Capture (Mpx/s)' },
                  { type: 'string', name: 'memory', label: 'Memory bandwidth' },
                  { type: 'string', name: 'price', label: 'Approx. price (USD)' },
                  { type: 'boolean', name: 'highlight', label: 'Highlight this row' },
                ],
              },
              { type: 'string', name: 'note', label: 'Footnote', ui: { component: 'textarea' } },
              { type: 'string', name: 'docUrl', label: 'Full benchmark docs URL' },
            ],
          },
          {
            type: 'object',
            name: 'closing',
            label: 'Closing CTA',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'gallery',
            label: 'More screenshots',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'shots',
                label: 'Screenshots',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.caption }) },
                fields: [
                  { type: 'image', name: 'image', label: 'Image' },
                  { type: 'string', name: 'caption', label: 'Caption' },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'install',
        label: 'Download & Install',
        path: 'content/install',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'title', label: 'Page title' },
          { type: 'string', name: 'lede', label: 'Intro paragraph', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'requirements',
            label: 'System requirements',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              { type: 'string', name: 'ramNote', label: 'RAM callout', ui: { component: 'textarea' } },
              { type: 'string', name: 'recommendedNote', label: 'Recommended-board callout', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'rows',
                label: 'Hardware rows',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.host }) },
                fields: [
                  { type: 'string', name: 'host', label: 'Host' },
                  { type: 'string', name: 'ram', label: 'RAM' },
                  { type: 'string', name: 'status', label: 'Status' },
                  { type: 'boolean', name: 'highlight', label: 'Highlight row' },
                  { type: 'string', name: 'tag', label: 'Badge (e.g. GPU + NPU, Top score)' },
                  { type: 'string', name: 'notes', label: 'Notes', ui: { component: 'textarea' } },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'images',
            label: 'Ready-to-flash images',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              { type: 'string', name: 'bootNote', label: 'Boot / hotspot callout', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'items',
                label: 'Image cards',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.device }) },
                fields: [
                  { type: 'string', name: 'device', label: 'Device' },
                  { type: 'string', name: 'badge', label: 'Badge (arch)' },
                  { type: 'string', name: 'color', label: 'Icon accent color (hex, optional)' },
                  { type: 'string', name: 'emoji', label: 'Icon emoji (optional, replaces the SVG)' },
                  { type: 'string', name: 'url', label: 'Download URL (empty = Coming soon)' },
                  { type: 'string', name: 'os', label: 'Base OS (optional)' },
                  { type: 'string', name: 'polaris', label: 'Polaris version (optional)' },
                  { type: 'string', name: 'size', label: 'File size (optional)' },
                  { type: 'string', name: 'access', label: 'First-boot access URL (optional)' },
                  { type: 'string', name: 'note', label: 'Note (optional)' },
                  {
                    type: 'string',
                    name: 'gpu',
                    label: 'GPU (OpenCL)',
                    options: [
                      { value: '', label: '(no badge)' },
                      { value: 'yes', label: 'Supported' },
                      { value: 'no', label: 'Not supported' },
                    ],
                  },
                  {
                    type: 'string',
                    name: 'npu',
                    label: 'NPU (AI)',
                    options: [
                      { value: '', label: '(no badge)' },
                      { value: 'yes', label: 'Supported' },
                      { value: 'no', label: 'Not supported' },
                    ],
                  },
                ],
              },
              {
                type: 'object',
                name: 'update',
                label: 'Update instructions',
                fields: [
                  { type: 'string', name: 'title', label: 'Title' },
                  { type: 'string', name: 'selfTitle', label: 'Self-update title' },
                  { type: 'string', name: 'selfBadge', label: 'Self-update badge' },
                  { type: 'string', name: 'selfBody', label: 'Self-update body', ui: { component: 'textarea' } },
                  { type: 'image', name: 'selfImage', label: 'Self-update screenshot' },
                  { type: 'string', name: 'manualTitle', label: 'Manual update title' },
                  { type: 'string', name: 'intro', label: 'Manual intro', ui: { component: 'textarea' } },
                  { type: 'string', name: 'code', label: 'Commands', ui: { component: 'textarea' } },
                  { type: 'string', name: 'note', label: 'Note', ui: { component: 'textarea' } },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'download',
            label: 'Download',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'groups',
                label: 'Download groups',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.name }) },
                fields: [
                  { type: 'string', name: 'name', label: 'Group name' },
                  { type: 'string', name: 'note', label: 'Group note', ui: { component: 'textarea' } },
                  {
                    type: 'object',
                    name: 'items',
                    label: 'Links',
                    list: true,
                    ui: { itemProps: (i) => ({ label: i?.label }) },
                    fields: [
                      { type: 'string', name: 'label', label: 'Label' },
                      { type: 'string', name: 'badge', label: 'Badge (arch)' },
                      { type: 'string', name: 'url', label: 'Download URL' },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'tldr',
            label: 'Bare-minimum table',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'note', label: 'Note', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'rows',
                label: 'Rows',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.label }) },
                fields: [
                  { type: 'string', name: 'label', label: 'Label' },
                  { type: 'string', name: 'windows', label: 'Windows' },
                  { type: 'string', name: 'linux', label: 'Linux' },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'platformsSection',
            label: 'Platforms heading',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'platforms',
            label: 'Platforms',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.name }) },
            fields: [
              { type: 'string', name: 'name', label: 'Name' },
              { type: 'string', name: 'badge', label: 'Badge' },
              { type: 'string', name: 'icon', label: 'Icon (chip, terminal, windows, container, code)' },
              { type: 'string', name: 'color', label: 'Icon accent color (hex)' },
              { type: 'string', name: 'summary', label: 'Summary', ui: { component: 'textarea' } },
              { type: 'string', name: 'steps', label: 'Install commands', ui: { component: 'textarea' } },
              { type: 'string', name: 'notes', label: 'Notes', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'firewall',
            label: 'Firewall',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              { type: 'string', name: 'windows', label: 'Windows commands', ui: { component: 'textarea' } },
              { type: 'string', name: 'linux', label: 'Linux commands', ui: { component: 'textarea' } },
              { type: 'string', name: 'note', label: 'Note', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'optionalSection',
            label: 'Optional components heading',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'optionalGroups',
            label: 'Optional components',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.name }) },
            fields: [
              { type: 'string', name: 'name', label: 'Group name' },
              { type: 'string', name: 'icon', label: 'Icon (plug, target, signal, wand, beaker, puzzle)' },
              { type: 'string', name: 'color', label: 'Icon accent color (hex)' },
              { type: 'string', name: 'intro', label: 'Intro', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'items',
                label: 'Components',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.name }) },
                fields: [
                  { type: 'string', name: 'name', label: 'Name' },
                  { type: 'string', name: 'badge', label: 'Badge' },
                  { type: 'string', name: 'purpose', label: 'Purpose', ui: { component: 'textarea' } },
                  { type: 'string', name: 'url', label: 'Link URL' },
                  { type: 'string', name: 'windows', label: 'Windows install' },
                  { type: 'string', name: 'linux', label: 'Linux install' },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'guide',
        label: 'Getting started',
        path: 'content/guide',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'title', label: 'Page title' },
          { type: 'string', name: 'lede', label: 'Intro paragraph', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'access',
            label: 'Access (how to open Polaris)',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'options',
                label: 'Access options',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.title }) },
                fields: [
                  { type: 'string', name: 'icon', label: 'Icon (emoji)' },
                  { type: 'string', name: 'title', label: 'Title' },
                  { type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
                  { type: 'string', name: 'code', label: 'Example URL (optional)' },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'steps',
            label: 'Steps',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.title }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Icon (emoji)' },
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
              { type: 'string', name: 'tip', label: 'Tip', ui: { component: 'textarea' } },
              { type: 'image', name: 'image', label: 'Screenshot' },
            ],
          },
          {
            type: 'object',
            name: 'closing',
            label: 'Closing',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'sub', label: 'Subtitle', ui: { component: 'textarea' } },
              { type: 'string', name: 'docUrl', label: 'Full docs URL' },
            ],
          },
        ],
      },
      {
        name: 'features',
        label: 'Features page',
        path: 'content/features',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'title', label: 'Page title' },
          { type: 'string', name: 'lede', label: 'Intro paragraph', ui: { component: 'textarea' } },
          { type: 'string', name: 'glanceTitle', label: 'At-a-glance heading' },
          {
            type: 'object',
            name: 'glance',
            label: 'At a glance',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.label }) },
            fields: [
              { type: 'string', name: 'label', label: 'Label (bold)' },
              { type: 'string', name: 'text', label: 'Text', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'sections',
            label: 'Panels',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.title }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Icon (emoji)' },
              { type: 'string', name: 'color', label: 'Accent color (hex)' },
              { type: 'string', name: 'title', label: 'Panel name' },
              { type: 'string', name: 'tag', label: 'Subtitle' },
              { type: 'string', name: 'intro', label: 'Intro', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'items',
                label: 'Feature bullets',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.label }) },
                fields: [
                  { type: 'string', name: 'label', label: 'Label (bold)' },
                  { type: 'string', name: 'text', label: 'Text', ui: { component: 'textarea' } },
                ],
              },
            ],
          },
          { type: 'string', name: 'docUrl', label: 'Full docs URL' },
          { type: 'string', name: 'docLabel', label: 'Docs link label' },
        ],
      },
      {
        name: 'aiTools',
        label: 'AI Tools page',
        path: 'content/ai-tools',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'title', label: 'Page title' },
          { type: 'string', name: 'lede', label: 'Intro paragraph', ui: { component: 'textarea' } },
          { type: 'string', name: 'glanceTitle', label: 'At-a-glance heading' },
          {
            type: 'object',
            name: 'glance',
            label: 'At a glance',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.label }) },
            fields: [
              { type: 'string', name: 'label', label: 'Label (bold)' },
              { type: 'string', name: 'text', label: 'Text', ui: { component: 'textarea' } },
            ],
          },
          { type: 'string', name: 'toolsTitle', label: 'Tools section heading' },
          {
            type: 'object',
            name: 'tools',
            label: 'Tools',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.title }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Icon (emoji)' },
              { type: 'string', name: 'color', label: 'Accent color (hex)' },
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'tag', label: 'Tag / subtitle' },
              {
                type: 'string',
                name: 'source',
                label: 'Model source',
                options: [
                  { value: 'graxpert', label: 'GraXpert model' },
                  { value: 'polaris', label: 'Polaris model' },
                  { value: 'polaris-soon', label: 'Polaris model (soon)' },
                  { value: 'classical', label: 'Algorithm' },
                ],
              },
              { type: 'string', name: 'intro', label: 'Intro', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'items',
                label: 'Bullet points',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.label ?? i?.text?.slice(0, 40) }) },
                fields: [
                  { type: 'string', name: 'label', label: 'Label (bold, optional)' },
                  { type: 'string', name: 'text', label: 'Text', ui: { component: 'textarea' } },
                ],
              },
            ],
          },
          { type: 'string', name: 'backendsTitle', label: 'Backends section heading' },
          { type: 'string', name: 'backendsLede', label: 'Backends intro', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'backends',
            label: 'Backends',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.title }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Icon (emoji)' },
              { type: 'string', name: 'color', label: 'Accent color (hex)' },
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'tag', label: 'Tag / subtitle' },
              { type: 'string', name: 'intro', label: 'Intro', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'items',
                label: 'Bullet points',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.label ?? i?.text?.slice(0, 40) }) },
                fields: [
                  { type: 'string', name: 'label', label: 'Label (bold, optional)' },
                  { type: 'string', name: 'text', label: 'Text', ui: { component: 'textarea' } },
                ],
              },
            ],
          },
          { type: 'string', name: 'precisionTitle', label: 'Precision section heading' },
          { type: 'string', name: 'precisionLede', label: 'Precision intro', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'precisions',
            label: 'Precisions',
            list: true,
            ui: { itemProps: (i) => ({ label: i?.name }) },
            fields: [
              { type: 'string', name: 'name', label: 'Name (e.g. fp32)' },
              { type: 'string', name: 'color', label: 'Accent color (hex)' },
              { type: 'string', name: 'tag', label: 'Badge label' },
              { type: 'string', name: 'desc', label: 'Description', ui: { component: 'textarea' } },
              { type: 'string', name: 'detail', label: 'Detail note', ui: { component: 'textarea' } },
            ],
          },
        ],
      },
      {
        name: 'about',
        label: 'About page',
        path: 'content/about',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'title', label: 'Page title' },
          { type: 'image', name: 'logo', label: 'Logo' },
          { type: 'string', name: 'lede', label: 'Intro paragraph', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'author',
            label: 'Author & contact',
            fields: [
              { type: 'string', name: 'title', label: 'Card title' },
              { type: 'string', name: 'intro', label: 'Intro' },
              { type: 'string', name: 'name', label: 'Name' },
              { type: 'string', name: 'email', label: 'Email' },
              { type: 'string', name: 'github', label: 'GitHub URL' },
              { type: 'string', name: 'linkedin', label: 'LinkedIn URL' },
              { type: 'string', name: 'astrobin', label: 'AstroBin URL' },
            ],
          },
          {
            type: 'object',
            name: 'license',
            label: 'License',
            fields: [
              { type: 'string', name: 'title', label: 'Card title' },
              { type: 'string', name: 'pre', label: 'Text before license link' },
              { type: 'string', name: 'licenseName', label: 'License name' },
              { type: 'string', name: 'licenseUrl', label: 'License URL' },
              { type: 'string', name: 'mid', label: 'Text between links' },
              { type: 'string', name: 'ninaName', label: 'Upstream name' },
              { type: 'string', name: 'ninaUrl', label: 'Upstream URL' },
              { type: 'string', name: 'post', label: 'Text after upstream link', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'version',
            label: 'Version & source',
            fields: [
              { type: 'string', name: 'title', label: 'Card title' },
              { type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'report',
            label: 'Report a problem',
            fields: [
              { type: 'string', name: 'title', label: 'Card title' },
              { type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'support',
            label: 'Support the project',
            fields: [
              { type: 'string', name: 'title', label: 'Card title' },
              { type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'credits',
            label: 'Credits & acknowledgements',
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'intro', label: 'Intro', ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'groups',
                label: 'Credit groups',
                list: true,
                ui: { itemProps: (i) => ({ label: i?.title }) },
                fields: [
                  { type: 'string', name: 'title', label: 'Group title' },
                  {
                    type: 'object',
                    name: 'items',
                    label: 'Projects',
                    list: true,
                    ui: { itemProps: (i) => ({ label: i?.name }) },
                    fields: [
                      { type: 'string', name: 'name', label: 'Name' },
                      { type: 'string', name: 'url', label: 'URL' },
                      { type: 'string', name: 'note', label: 'Note', ui: { component: 'textarea' } },
                    ],
                  },
                ],
              },
              { type: 'string', name: 'outro', label: 'Outro', ui: { component: 'textarea' } },
            ],
          },
        ],
      },
    ],
  },
});
