#!/usr/bin/env bash
# Post-`cap add android` fixups: patch the AndroidManifest.
#
# The `android/` folder is git-ignored (regenerated by `npx cap add
# android`), so these don't survive a fresh `cap add`. Run this ONCE after
# `cap add android` (and again after any future `cap add android`):
#
#   cd mobile
#   npx cap add android
#   ./scripts/android-postadd.sh
#   npx cap sync android
#
# Idempotent: re-running is a no-op if the attributes are already present.
set -euo pipefail

MANIFEST="android/app/src/main/AndroidManifest.xml"

if [ ! -f "$MANIFEST" ]; then
  echo "error: $MANIFEST not found. Run 'npx cap add android' first (from mobile/)." >&2
  exit 1
fi

echo "Patching $MANIFEST …"

# The Polaris UI is a WebGL + WASM SPA; on some Android System WebViews a
# powerful tablet can ANR under GC pressure. largeHeap + hardwareAccelerated
# on <application> mitigate it. Add each only if missing (no dup attrs).
grep -q 'android:largeHeap' "$MANIFEST" || \
  perl -0pi -e 's/(<application\b)/$1 android:largeHeap="true"/' "$MANIFEST"
grep -q 'android:hardwareAccelerated' "$MANIFEST" || \
  perl -0pi -e 's/(<application\b)/$1 android:hardwareAccelerated="true"/' "$MANIFEST"

echo "Done. Next: npx cap sync android"
