#!/usr/bin/env bash
# Post-`cap add ios` fixups: patch Info.plist + Podfile, then pod install.
#
# The `ios/` folder is git-ignored (regenerated by `npx cap add ios`), so
# none of this survives a fresh `cap add`. Run this ONCE after
# `cap add ios` (and again after any future `cap add ios`):
#
#   cd mobile
#   npx cap add ios          # its own pod install fails — expected
#   ./scripts/ios-postadd.sh # patches + runs pod install for real
#   npx cap open ios
#
# macOS only (uses /usr/libexec/PlistBuddy + CocoaPods).
set -euo pipefail

PLIST="ios/App/App/Info.plist"
PODFILE="ios/App/Podfile"
PB=/usr/libexec/PlistBuddy

if [ ! -f "$PLIST" ]; then
  echo "error: $PLIST not found. Run 'npx cap add ios' first (from mobile/)." >&2
  exit 1
fi

set_string() {  # key, value
  "$PB" -c "Delete :$1" "$PLIST" 2>/dev/null || true
  "$PB" -c "Add :$1 string $2" "$PLIST"
}

echo "Patching $PLIST …"

# @capacitor/geolocation crashes on the permission prompt without this.
set_string "NSLocationWhenInUseUsageDescription" \
  "Polaris uses your location for polar-alignment and target planning."

# iOS 14+ Local Network permission (mDNS discovery + LAN sockets).
set_string "NSLocalNetworkUsageDescription" \
  "Polaris finds your telescope controller on the local network."

# App Transport Security: allow the self-signed LAN HTTPS / local hosts.
"$PB" -c "Delete :NSAppTransportSecurity" "$PLIST" 2>/dev/null || true
"$PB" -c "Add :NSAppTransportSecurity dict" "$PLIST"
"$PB" -c "Add :NSAppTransportSecurity:NSAllowsLocalNetworking bool true" "$PLIST"

# Bonjour service type Polaris advertises (MdnsService registers `_nina._tcp`)
# and that connect.js browses. iOS 14+ BLOCKS an mDNS browse whose type isn't
# listed here, so this MUST match `_nina._tcp` exactly or discovery finds
# nothing. (_http._tcp kept as a harmless extra.)
"$PB" -c "Delete :NSBonjourServices" "$PLIST" 2>/dev/null || true
"$PB" -c "Add :NSBonjourServices array" "$PLIST"
"$PB" -c "Add :NSBonjourServices:0 string _nina._tcp" "$PLIST"
"$PB" -c "Add :NSBonjourServices:1 string _http._tcp" "$PLIST"

# ---- Inject LANCertTrust.swift so WKWebView accepts the LAN self-signed cert ----
# The Polaris UI iframe loads over the SBC's self-signed HTTPS; WKWebView
# rejects it by default (no "proceed anyway"), leaving the tab blank. This
# Swift extension adds a server-trust challenge handler scoped to LAN hosts.
# `ios/` is regenerated by `cap add`, so copy the tracked source in and
# register it in the Xcode project every time.
SRC="ios-src/LANCertTrust.swift"
DEST="ios/App/App/LANCertTrust.swift"
if [ -f "$SRC" ]; then
  echo "Injecting $DEST …"
  cp "$SRC" "$DEST"
  gem list -i xcodeproj >/dev/null 2>&1 || gem install --no-document xcodeproj >/dev/null
  ruby - <<'RUBY'
require 'xcodeproj'
proj = Xcodeproj::Project.open('ios/App/App.xcodeproj')
app = proj.targets.find { |t| t.name == 'App' }
group = proj.main_group.find_subpath('App', true)
unless group.files.any? { |f| f.display_name == 'LANCertTrust.swift' }
  ref = group.new_file('LANCertTrust.swift')
  app.source_build_phase.add_file_reference(ref)
  proj.save
  puts 'Registered LANCertTrust.swift in App target'
else
  puts 'LANCertTrust.swift already registered'
end
RUBY
else
  echo "warning: $SRC missing — skipping LAN cert trust injection" >&2
fi

# ---- Podfile: onnxruntime needs iOS 14 + STATIC linkage ----
if [ -f "$PODFILE" ]; then
  echo "Patching $PODFILE …"
  # onnxruntime-objc / -c require a deployment target >= 14.0; Capacitor's
  # generated Podfile pins 13.0.
  perl -0pi -e "s/platform :ios, '[0-9.]*'/platform :ios, '14.0'/" "$PODFILE"
  # onnxruntime ships STATIC binaries, which error out under a dynamic
  # `use_frameworks!` ("transitive dependencies that include statically
  # linked binaries"). Switch the whole Podfile to STATIC linkage: drop any
  # existing use_frameworks! line and add a static one after the platform.
  perl -0pi -e 's/^[ \t]*use_frameworks!.*\n//mg' "$PODFILE"
  perl -0pi -e "s/(^platform :ios[^\n]*\n)/\$1use_frameworks! :linkage => :static\n/m" "$PODFILE"
fi

echo "Running pod install …"
( cd ios/App && pod install )

echo "Done. Next: npx cap open ios"
