#!/usr/bin/env bash
# Post-`cap add ios` fixups: patch Info.plist + Podfile, then pod install.
#
# The `ios/` folder is git-ignored (regenerated by `npx cap add ios`), so
# none of this survives a fresh `cap add`. Run this ONCE after
# `cap add ios` (and again after any future `cap add ios`):
#
#   cd mobile
#   npx cap add ios          # its own pod install fails — expected
#   ./scripts/ios-postadd.sh # patches + runs pod install for real
#   npx cap open ios
#
# macOS only (uses /usr/libexec/PlistBuddy + CocoaPods).
set -euo pipefail

PLIST="ios/App/App/Info.plist"
PODFILE="ios/App/Podfile"
PB=/usr/libexec/PlistBuddy

if [ ! -f "$PLIST" ]; then
  echo "error: $PLIST not found. Run 'npx cap add ios' first (from mobile/)." >&2
  exit 1
fi

set_string() {  # key, value
  "$PB" -c "Delete :$1" "$PLIST" 2>/dev/null || true
  "$PB" -c "Add :$1 string $2" "$PLIST"
}

echo "Patching $PLIST …"

# @capacitor/geolocation crashes on the permission prompt without this.
set_string "NSLocationWhenInUseUsageDescription" \
  "Polaris uses your location for polar-alignment and target planning."

# iOS 14+ Local Network permission (mDNS discovery + LAN sockets).
set_string "NSLocalNetworkUsageDescription" \
  "Polaris finds your telescope controller on the local network."

# App Transport Security: allow the self-signed LAN HTTPS / local hosts.
"$PB" -c "Delete :NSAppTransportSecurity" "$PLIST" 2>/dev/null || true
"$PB" -c "Add :NSAppTransportSecurity dict" "$PLIST"
"$PB" -c "Add :NSAppTransportSecurity:NSAllowsLocalNetworking bool true" "$PLIST"

# Bonjour services advertised by the Pi (for capacitor-zeroconf discovery).
"$PB" -c "Delete :NSBonjourServices" "$PLIST" 2>/dev/null || true
"$PB" -c "Add :NSBonjourServices array" "$PLIST"
"$PB" -c "Add :NSBonjourServices:0 string _polaris._tcp" "$PLIST"
"$PB" -c "Add :NSBonjourServices:1 string _http._tcp" "$PLIST"

# ---- Podfile: onnxruntime needs iOS 14 + static linkage ----
if [ -f "$PODFILE" ]; then
  echo "Patching $PODFILE …"
  # onnxruntime-objc / -c require a deployment target >= 14.0; Capacitor's
  # generated Podfile pins 13.0. (-i.bak works on both BSD + GNU sed.)
  sed -i.bak "s/platform :ios, '[0-9.]*'/platform :ios, '14.0'/" "$PODFILE"
  rm -f "$PODFILE.bak"
  # onnxruntime ships STATIC binaries, which clash with use_frameworks!
  # (dynamic) that Capacitor sets. Force just those pods to static so
  # pod install stops erroring on "statically linked binaries".
  if ! grep -q "POLARIS_ONNX_STATIC" "$PODFILE"; then
    cat >> "$PODFILE" <<'RUBY'

# POLARIS_ONNX_STATIC — keep the onnxruntime pods statically linked so they
# don't conflict with Capacitor's dynamic use_frameworks!.
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if ['onnxruntime-objc', 'onnxruntime-c'].include?(pod.name)
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end
RUBY
  fi
fi

echo "Running pod install …"
( cd ios/App && pod install )

echo "Done. Next: npx cap open ios"
